" JAVASCRIPT "
Plug 'chemzqm/vim-jsx-improve'
Plug 'mattn/emmet-vim'
Plug 'jrmmendes/vim-vue'
Plug 'cakebaker/scss-syntax.vim'
Plug 'leafgarland/typescript-vim'
Plug 'evanleck/vim-svelte'
Plug 'peitalin/vim-jsx-typescript'
Plug 'othree/javascript-libraries-syntax.vim'
"Plug ''
